### ISSUE TITLE
precommit check?

### ISSUE THREAD

**Issue by kirrg001** [cst/cst#129]
Hey,

since today i am getting a pre commit check. I removed my node_modules in the morning and did a fresh install, then i got this output on every git commit.

1. i think the folder `src` is not in the release folder, that's why it says `Error: Path src was not found.`
2. Is there a way to disable pre commit check?

node v4.4.5

```
git commit -am "test"

> cst@0.4.3 precommit .../node_modules/grunt-jscs/node_modules/jscs/node_modules/cst
> npm test


> cst@0.4.3 test .../node_modules/grunt-jscs/node_modules/jscs/node_modules/cst
> npm run lint && npm run test:unit


> cst@0.4.3 lint .../node_modules/grunt-jscs/node_modules/jscs/node_modules/cst
> npm run lint:jscs


> cst@0.4.3 lint:jscs .../node_modules/grunt-jscs/node_modules/jscs/node_modules/cst
> jscs src test

Error: Path src was not found.
    at [object Object].<anonymous> (.../node_modules/grunt-jscs/node_modules/jscs/lib/checker.js:185:19)
    at Array.0 (..../node_modules/grunt-jscs/node_modules/vow/lib/vow.js:712:39)
    at Object.callFns [as _onImmediate] (....node_modules/grunt-jscs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:363:15)

npm ERR! Darwin 15.5.0
npm ERR! argv "..../.nvm/v0.10.45/bin/node" "....nvm/v0.10.45/bin/npm" "run" "lint:jscs"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! cst@0.4.3 lint:jscs: `jscs src test`
````

**Comment by hzoo** [comment]
I'm kind of confused what's going on there - this isn't for `cst` itself right? It definetely shouldn't be running a pre-commit hook for your own code.

**Comment by kirrg001** [comment]
i have no clue, it came after removing node_modules in the morning and i use `grunt-jscs`.

**Comment by markelog** [comment]
You probably deleted `src` folder

> Is there a way to disable pre commit check?

`git commit -n`
