### ISSUE TITLE
Fails to parse trailing coma in constructor call

### ISSUE THREAD

**Issue by graingert** [cst/cst#142]
```
> new (require('cst').Parser)().parse('new Promise(executor,)')
Error: Expression expected but "Punctuator" found
    at ElementAssert._passExpressionInParens (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/ElementAssert.js:316:19)
    at ElementAssert.passExpression (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/ElementAssert.js:256:21)
    at NewExpression._acceptChildren (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/types/NewExpression.js:28:40)
    at NewExpression._setChildren (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/Element.js:639:14)
    at NewExpression.Element (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/Element.js:50:18)
    at NewExpression.Node (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/Node.js:11:33)
    at NewExpression.Expression (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/Expression.js:13:33)
    at new NewExpression (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elements/types/NewExpression.js:4:29)
    at buildElementTreeItem (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elementTree.js:146:24)
    at buildElementTreeItem (/home/graingert/projects/procensus/frontend/node_modules/cst/src/elementTree.js:119:45)
```

**Comment by Yeti-or** [comment]
@graingert but it is not valid js

**Comment by graingert** [comment]
Yes it is.

```
$ node --harmony_trailing_commas
> console.log('foo',)
foo
undefined
> new Date('3',)
2001-03-01T00:00:00.000Z
> 
(To exit, press ^C again or type .exit)
>
```

**Comment by Yeti-or** [comment]
very useful by the way :trollface:

**Comment by graingert** [comment]
@Yeti-or it's now mandatory in airbnb: https://github.com/airbnb/javascript/commit/788208295469e19b806c06e01095dc8ba1b6cdc9

**Comment by graingert** [comment]
> very useful by the way :trollface:

?

**Comment by markelog** [comment]
Just out of curiosity when this became part of the spec?

Seems another thing for minifiers to be concern about :)

**Comment by graingert** [comment]
@markelo 2017?

**Comment by graingert** [comment]
Re: minifiers, the developers of babili and closure-compiler are up to date with and involved in the dealings of TC39 so of it was something they'd have to worry about I imagine they'd get it fixed before it got past stage-3
